config/routes.rb
Rails.application.routes.draw do
  resource :calendar, only: [:show], controller: :calendar
  resources :events, only: [:new, :show, :edit, :destroy]
  root to: "calendar#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @events_by_date = Event.all
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def show
        @event = Event.find(params[:id])
    end
    
    def edit
        @event = Event.find(params[:id])
    end

    def update

    end

    def destroy
        event = Event.find(params[:id])
        event.delete
        redirect_to "/" 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
    def calendar(date = Date.today, &block)
      Calendar.new(self, date, block).table
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/calendar/show.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-backward"></i>
      <% end %>
      <%= "#{@date.strftime("%B")} #{@date.year}" %>
      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
        <i class="glyphicon glyphicon-forward"></i>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
  <%= calendar @date do |date| %>
    <%= date.day %>
    <ul> 
        <% @events_by_date.each do |t| %> 
            <% if t.date == date %> 
                <li><%= link_to(t.type_of_shift, t)%></li> 
            <% end %> 
        <% end %> 
    </ul>
  <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="row">
    <h2> <%=@event.type_of_shift%> shift </h2>
</div>

<%= link_to "Edit", edit_event_path(@event) %>
<%= link_to "Delete", 
            event_path(@event), 
            method: :delete,
            data: { confirm: 'Are you sure?' }%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalendarExample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>
  <%= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>

</body>
</html>